mode = "dark"

accent = "#00a0e4"
selection = "#494949"
muted = "#5b5b5b"

hyprland_active_border = "#00a0e4 #494949 90deg"
hyprland_inactive_border = "#494949"

background = "#0d0d0d"
dark_background = "#151515"
darker_background = "#050505"
lighter_background = "#3a3a3a"

foreground = "#d6d4d3"
dark_foreground = "#7f7f7f"
light_foreground = "#e6e4e3"
bright_foreground = "#ffffff"

red = "#da2c20"
yellow = "#fcec02"
orange = "#e06a1a"
green = "#00a152"
cyan = "#b5e4f4"
blue = "#00a0e4"
magenta = "#a06994"
brown = "#8a5230"

bright_red = "#e8bacf"
bright_yellow = "#494949"
bright_green = "#3a3a3a"
bright_cyan = "#ccab53"
bright_blue = "#7f7f7f"
bright_magenta = "#d6d4d3"
