mode = "dark"

accent = "#00a0e4"
selection = "#494542"
muted = "#5b5754"

hyprland_active_border = "#00a0e4 #494542 90deg"
hyprland_inactive_border = "#494542"

background = "#090200"
dark_background = "#14100d"
darker_background = "#020100"
lighter_background = "#3a3332"

foreground = "#d6d4d3"
dark_foreground = "#7f7c7b"
light_foreground = "#e6e4e3"
bright_foreground = "#ffffff"

red = "#da2c20"
yellow = "#fcec02"
orange = "#e06a1a"
green = "#00a152"
cyan = "#b5e4f4"
blue = "#00a0e4"
magenta = "#a06994"
brown = "#8a5230"

bright_red = "#e8bacf"
bright_yellow = "#494542"
bright_green = "#3a3332"
bright_cyan = "#ccab53"
bright_blue = "#7f7c7b"
bright_magenta = "#d6d4d3"
