text             = "#a9b1d6"
placeholder      = "#565f89"
text-error       = "#f7768e"
border           = "hyprland.active-border"
border-active    = "hyprland.active-border"
border-error     = "#f7768e"
