background       = "#090200"
background-alpha = 0.85
text             = "#d6d4d3"
active           = "#da2c20"
border           = "hyprland.active-border"
scale-with-font  = true
size-horizontal  = 26
size-vertical    = 28
