[menu]
background            = "#0d0d0d"
background-alpha      = 0.85
text                  = "#5b5b5b"
border                = "hyprland.active-border"
border-alpha          = 1.0
selected-border       = "#00a0e4"
selected-border-alpha = 1.0
selected-border-width = 2
